# Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[-1]

np.int64(10)

In [7]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice_of_arr = arr.copy()

In [29]:
slice_of_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice_of_arr[:5] = 90

In [32]:
slice_of_arr

array([90, 90, 90, 90, 90,  5,  6,  7,  8,  9, 10])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[0][2]

np.int64(15)

In [37]:
arr_2d[2][1]

np.int64(40)

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [44]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [45]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
bool_arr = arr > 5

In [49]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [50]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr<3]

array([0, 1, 2])

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations

#### array with array

In [58]:
arr = np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### array with scalar

In [63]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [64]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [65]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [66]:
arr /4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ])

In [67]:
1/0

ZeroDivisionError: division by zero

In [68]:
arr / arr

C:\Users\CHANDRU DEIVANAYAGAN\AppData\Local\Temp\ipykernel_5500\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
1 / arr

C:\Users\CHANDRU DEIVANAYAGAN\AppData\Local\Temp\ipykernel_5500\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [70]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
arr ** 7

array([       0,        1,      128,     2187,    16384,    78125,
         279936,   823543,  2097152,  4782969, 10000000])

#### universal array functions

In [72]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [73]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [74]:
arr.max()

np.int64(10)

In [75]:
arr.min()

np.int64(0)

In [76]:
arr.argmax()

np.int64(10)

In [78]:
arr.argmin()

np.int64(0)

In [79]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [80]:
np.log(arr)

C:\Users\CHANDRU DEIVANAYAGAN\AppData\Local\Temp\ipykernel_5500\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])