# Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
type(np.array(my_list))

numpy.ndarray

In [6]:
arr = np.array(my_list)

In [7]:
type(arr)

numpy.ndarray

In [8]:
lose = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
arr2 = np.array([lose])

In [10]:
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
type(arr2)

numpy.ndarray

In [12]:
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [13]:
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [17]:
array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [20]:
numbers = np.arange(0,11,2)

In [21]:
numbers

array([ 0,  2,  4,  6,  8, 10])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [31]:
np.linspace(0,7,100)

array([0.        , 0.07070707, 0.14141414, 0.21212121, 0.28282828,
       0.35353535, 0.42424242, 0.49494949, 0.56565657, 0.63636364,
       0.70707071, 0.77777778, 0.84848485, 0.91919192, 0.98989899,
       1.06060606, 1.13131313, 1.2020202 , 1.27272727, 1.34343434,
       1.41414141, 1.48484848, 1.55555556, 1.62626263, 1.6969697 ,
       1.76767677, 1.83838384, 1.90909091, 1.97979798, 2.05050505,
       2.12121212, 2.19191919, 2.26262626, 2.33333333, 2.4040404 ,
       2.47474747, 2.54545455, 2.61616162, 2.68686869, 2.75757576,
       2.82828283, 2.8989899 , 2.96969697, 3.04040404, 3.11111111,
       3.18181818, 3.25252525, 3.32323232, 3.39393939, 3.46464646,
       3.53535354, 3.60606061, 3.67676768, 3.74747475, 3.81818182,
       3.88888889, 3.95959596, 4.03030303, 4.1010101 , 4.17171717,
       4.24242424, 4.31313131, 4.38383838, 4.45454545, 4.52525253,
       4.5959596 , 4.66666667, 4.73737374, 4.80808081, 4.87878788,
       4.94949495, 5.02020202, 5.09090909, 5.16161616, 5.23232

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
np.random.rand(6) # it will give us uniform distribution

array([0.29881856, 0.60149479, 0.13638342, 0.44572297, 0.39586376,
       0.5660023 ])

In [39]:
np.random.rand(5,5)

array([[0.783844  , 0.68742208, 0.4561462 , 0.76727514, 0.01032258],
       [0.73340624, 0.24150176, 0.44685047, 0.14475056, 0.69904126],
       [0.13450513, 0.60700421, 0.51564161, 0.99719475, 0.13703864],
       [0.00118638, 0.99318393, 0.13314558, 0.31350057, 0.60584658],
       [0.78879246, 0.71582602, 0.0891581 , 0.98001016, 0.90036422]])

In [40]:
np.random.randn(2)

array([0.41307331, 1.63132209])

In [41]:
np.random.randn(10)

array([ 0.35128607, -0.67273775, -0.04346928, -0.05536266,  1.02808888,
        0.64442675,  0.50963849, -1.32326552,  1.28028483, -0.25947135])

In [43]:
np.random.randn(10,10) # it will give us standard normal distribution

array([[-0.29078453,  0.12658851,  0.12805256,  0.78845556, -1.21486544,
         0.26627387, -1.16019582, -0.26668935, -0.54695807,  0.71431096],
       [ 0.86519006, -1.25520066,  0.07230182,  0.91420867,  0.70652   ,
        -0.52852012, -1.34064251,  0.24101147,  0.77594689,  0.82906464],
       [ 0.2466122 ,  0.89037697,  0.51016381,  1.27442139,  0.80731771,
         1.33627205,  0.11696619,  0.92643288, -0.19343875, -1.76037179],
       [-0.29607609, -1.18532333, -0.54786892,  0.59941581, -0.05880159,
         0.37258286, -1.18306334, -0.18885869, -0.32399142,  0.60736429],
       [ 0.91575792,  1.01368569, -0.73230452, -0.21319416, -1.47033784,
        -0.27885865,  2.15575955,  1.49833663, -0.69656688, -0.58229568],
       [-0.08970913,  0.15728198,  0.27727471, -0.94705553, -0.12335416,
         2.72377181,  0.28306978, -0.28253672,  1.82650412,  0.02927816],
       [ 0.70556841, -0.36973476,  0.31490494, -1.6019798 , -0.4653037 ,
         0.40911019,  0.27774361,  0.16796833

In [44]:
np.random.randint(1,100)

22

In [45]:
np.random.randint(1,100,10)

array([ 2, 84, 53, 92, 60, 73, 92, 62, 69, 32], dtype=int32)

In [46]:
arr = np.arange(50)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
ranarr = np.random.randint(0,100,10)

In [49]:
ranarr

array([96, 87,  2, 37, 62, 49,  2, 89, 56,  0], dtype=int32)

In [52]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [53]:
arr = arr.reshape(10,5)

In [54]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [55]:
ranarr.max()

np.int32(96)

In [56]:
ranarr.min()

np.int32(0)

In [57]:
ranarr.argmax()

np.int64(0)

In [58]:
ranarr.argmin()

np.int64(9)

In [60]:
ranarr.shape

(10,)

In [61]:
arr.shape

(10, 5)

In [63]:
arr.dtype

dtype('int64')