## LOGISTIC REGRESSION

### IMPORT NECESSARY LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

### DATA COLLECTION

In [2]:
claiments_data = pd.read_csv(filepath_or_buffer="claiments.csv")

### DATA UNDERSTANDING

In [3]:
claiments_data.head()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,5,0,0.0,1.0,0.0,50.0,34.940
1,3,1,1.0,0.0,0.0,18.0,0.891
2,66,1,0.0,1.0,0.0,5.0,0.330
3,70,0,0.0,1.0,1.0,31.0,0.037
4,96,1,0.0,1.0,0.0,30.0,0.038


In [4]:
claiments_data.shape

(1340, 7)

In [5]:
claiments_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [6]:
claiments_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   CASENUM   1340 non-null   int64  
 1   ATTORNEY  1340 non-null   int64  
 2   CLMSEX    1328 non-null   float64
 3   CLMINSUR  1299 non-null   float64
 4   SEATBELT  1292 non-null   float64
 5   CLMAGE    1151 non-null   float64
 6   LOSS      1340 non-null   float64
dtypes: float64(5), int64(2)
memory usage: 73.4 KB


In [7]:
claiments_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

### DATA PREPARATION

In [8]:
claiments_data.head()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,5,0,0.0,1.0,0.0,50.0,34.940
1,3,1,1.0,0.0,0.0,18.0,0.891
2,66,1,0.0,1.0,0.0,5.0,0.330
3,70,0,0.0,1.0,1.0,31.0,0.037
4,96,1,0.0,1.0,0.0,30.0,0.038


In [9]:
claiments_data.dropna(inplace=True)

In [10]:
claiments_data.shape

(1096, 7)

In [11]:
claiments_data.isnull().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

#### SPLITTING THE DATASET INTO X AND Y(INDEPENDENT AND DEPENDENT)

#### TRAIN TEST SPLIT

In [12]:
X = claiments_data.drop(labels=["ATTORNEY","CASENUM"],axis=1)

In [13]:
y = claiments_data[["ATTORNEY"]]

In [14]:
X

,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0.0,1.0,0.0,50.0,34.940
1,1.0,0.0,0.0,18.0,0.891
2,0.0,1.0,0.0,5.0,0.330
3,0.0,1.0,1.0,31.0,0.037
4,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...
1334,1.0,1.0,0.0,16.0,0.060
1336,1.0,1.0,0.0,46.0,3.705
1337,1.0,1.0,0.0,39.0,0.099
1338,1.0,0.0,0.0,8.0,3.177


In [15]:
y

,ATTORNEY
0,0
1,1
2,1
3,0
4,1
...,...
1334,1
1336,0
1337,1
1338,0


#### K FOLD CV

In [16]:
from sklearn.model_selection import KFold, cross_val_score

In [22]:
kfold=KFold(n_splits=5,shuffle=True,random_state=101)

cv_scores = cross_val_score(estimator=logistic_model,X=X,y=y,cv=kfold)

In [27]:
print(cv_scores)

print("Overall Accuracy: ",cv_scores.mean().round(2))
print("Overall Std-Dev: ",cv_scores.std().round(2))

[0.68636364 0.69863014 0.73059361 0.74885845 0.67123288]
Overall Accuracy:  0.71
Overall Std-Dev:  0.03


### LOOCV = LEAVE ONE OUT CROSS VALIDATION

In [26]:
from sklearn.model_selection import LeaveOneOut

In [28]:
loocv = LeaveOneOut()

cv_scores = cross_val_score(estimator=logistic_model,X=X,y=y,cv=loocv)

print(cv_scores)

print("Overall Accuracy: ",cv_scores.mean().round(2))
print("Overall Std-Dev: ",cv_scores.std().round(2))

[1. 1. 1. ... 1. 1. 1.]
Overall Accuracy:  0.7
Overall Std-Dev:  0.46


### MODEL BUILDING

In [17]:
logistic_model = LogisticRegression()

### MODEL TRAINING

In [18]:
logistic_model.fit(X,y)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


### MODEL TESTING

In [19]:
y_pred = logistic_model.predict(X)

In [20]:
y_pred

array([0, 1, 1, ..., 1, 0, 1], shape=(1096,))

### MODEL EVALUATION

In [22]:
accuracy_score(y,y_pred)

0.708029197080292

### MODEL DEPLOYMENT

In [23]:
from pickle import dump

In [26]:
dump(logistic_model,open("claiments.pkl",mode="wb"))