### MODEL EVAKVALIDATION (TESTs)

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split,KFold,cross_val_score,LeaveOneOut

In [3]:
claiments_data = pd.read_csv("claiments.csv")

In [4]:
claiments_data.head()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,5,0,0.0,1.0,0.0,50.0,34.940
1,3,1,1.0,0.0,0.0,18.0,0.891
2,66,1,0.0,1.0,0.0,5.0,0.330
3,70,0,0.0,1.0,1.0,31.0,0.037
4,96,1,0.0,1.0,0.0,30.0,0.038


In [5]:
claiments_data.shape

(1340, 7)

In [6]:
claiments_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [7]:
claiments_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [8]:
claiments_data.dropna(inplace=True)

In [9]:
claiments_data.isnull().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [10]:
claiments_data.head()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,5,0,0.0,1.0,0.0,50.0,34.940
1,3,1,1.0,0.0,0.0,18.0,0.891
2,66,1,0.0,1.0,0.0,5.0,0.330
3,70,0,0.0,1.0,1.0,31.0,0.037
4,96,1,0.0,1.0,0.0,30.0,0.038


In [13]:
X = claiments_data.drop(labels=["CASENUM","ATTORNEY"],axis=1)

In [14]:
y = claiments_data["ATTORNEY"]

In [15]:
log_model = LogisticRegression()

In [16]:
log_model.fit(X,y)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [17]:
y_pred = log_model.predict(X)

In [18]:
y_pred

array([0, 1, 1, ..., 1, 0, 1], shape=(1096,))

### first technique ===== TRAIN TEST SPLIT

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=101,shuffle=True)

In [21]:
X_train

,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
1306,1.0,1.0,0.0,38.0,0.005
58,1.0,1.0,0.0,44.0,0.139
419,0.0,0.0,0.0,50.0,3.719
1172,0.0,1.0,0.0,13.0,0.746
189,1.0,0.0,0.0,65.0,0.373
...,...,...,...,...,...
702,1.0,1.0,0.0,40.0,3.570
1188,1.0,1.0,0.0,44.0,13.000
92,1.0,1.0,0.0,8.0,0.860
729,0.0,1.0,0.0,11.0,0.500


In [22]:
X_test

,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
759,0.0,0.0,0.0,30.0,9.909
887,0.0,1.0,0.0,77.0,0.050
1266,1.0,1.0,0.0,37.0,0.193
1083,1.0,1.0,0.0,35.0,1.713
480,0.0,1.0,0.0,47.0,0.090
...,...,...,...,...,...
215,1.0,1.0,0.0,77.0,0.944
257,0.0,1.0,0.0,15.0,3.070
907,0.0,1.0,0.0,39.0,8.815
645,0.0,1.0,0.0,17.0,5.118


In [23]:
y_train

1306    1
58      1
419     0
1172    1
189     1
       ..
702     0
1188    0
92      1
729     1
1060    0
Name: ATTORNEY, Length: 876, dtype: int64

In [24]:
y_test

759     0
887     1
1266    1
1083    1
480     1
       ..
215     1
257     0
907     0
645     0
365     1
Name: ATTORNEY, Length: 220, dtype: int64

In [25]:
log_model.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [27]:
y_pred_train = log_model.predict(X_train)
y_pred_train

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,

In [28]:
y_pred_test = log_model.predict(X_test)
y_pred_test

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [31]:
accuracy_score(y_train,y_pred_train)

0.70662100456621

In [32]:
accuracy_score(y_test,y_pred_test)

0.6863636363636364

### second technique ===== K-FOLD CROSS VALIDATION

In [37]:
#1

In [34]:
k_fold =KFold(n_splits=5, shuffle=True, random_state=101)
cv_scores = cross_val_score(estimator=log_model,
    X=X,
    y=y,
    cv=k_fold)

In [36]:
print(cv_scores)

print("Overall Accuracy: ",cv_scores.mean().round(2))
print("Overall Standard Deviation: ",cv_scores.std().round(2))

[0.68636364 0.69863014 0.73059361 0.74885845 0.67123288]
Overall Accuracy:  0.71
Overall Standard Deviation:  0.03


In [38]:
#2

In [39]:
k_fold =KFold(n_splits=5, shuffle=True, random_state=101)
cv_scores = cross_val_score(estimator=log_model,
    X=X_train,
    y=y_train,
    cv=k_fold)

In [40]:
print(cv_scores)

print("Overall Accuracy: ",cv_scores.mean().round(2))
print("Overall Standard Deviation: ",cv_scores.std().round(2))

[0.72159091 0.70857143 0.69142857 0.76       0.62857143]
Overall Accuracy:  0.7
Overall Standard Deviation:  0.04


### third technique ===== Leave one out cross validation

In [43]:
#1

In [42]:
loocv = LeaveOneOut()

cv_scores = cross_val_score(estimator=log_model,
    X=X,
    y=y,
    cv=loocv)

In [44]:
print(cv_scores)

print("Overall Accuracy: ",cv_scores.mean().round(2))
print("Overall Standard Deviation: ",cv_scores.std().round(2))

[1. 1. 1. ... 1. 1. 1.]
Overall Accuracy:  0.7
Overall Standard Deviation:  0.46


In [45]:
#2

In [46]:
loocv = LeaveOneOut()

cv_scores = cross_val_score(estimator=log_model,
    X=X_train,
    y=y_train,
    cv=loocv)

In [47]:
print(cv_scores)

print("Overall Accuracy: ",cv_scores.mean().round(2))
print("Overall Standard Deviation: ",cv_scores.std().round(2))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1.
 0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1.
 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1.